const fs=require('node:fs'),vm=require('node:vm'),assert=require('node:assert/strict');
const html=fs.readFileSync('crm/index.html','utf8');
for(const [,source] of html.matchAll(/<script(?:\s[^>]*)?>([\s\S]*?)<\/script>/g))new vm.Script(source);
function fn(name){const start=html.indexOf('async function '+name+'(');const end=html.indexOf('\nfunction ',start);const asyncEnd=html.indexOf('\nasync function ',start+1);return html.slice(start,Math.min(...[end,asyncEnd].filter(x=>x>=0)));}
function context(){const calls=[],fields={apptFormLeadId:{value:'7'},apptFormCustomerName:{value:'Test'},apptFormMobile:{value:'9000000000'},apptFormDate:{value:'2026-10-10'},apptFormTime:{value:'10:30'},apptFormStatus:{value:'Scheduled'},apptFormNotes:{value:''}},button={textContent:'Save',disabled:false};const modal={dataset:{appointmentId:'42',rescheduleMode:'1'},querySelector:()=>button};fields.appointmentFormModal=modal;const c={calls,fields,button,modal,appointmentSaveInProgress:false,currentEditingAppointmentId:999,currentUser:{id:'owner'},document:{getElementById:id=>fields[id]},alert:m=>calls.push(['alert',m]),console,updateAppointment:async(id,p)=>{calls.push(['update',id,p]);return true;},saveAppointment:async()=>{calls.push(['insert']);return true;},closeAppointmentFormModal:()=>calls.push(['close']),sendAppointmentRescheduleWhatsApp:async()=>calls.push(['whatsapp'])};vm.createContext(c);vm.runInContext(fn('saveAppointmentFromForm'),c);return c;}
(async()=>{
let c=context();await c.saveAppointmentFromForm();assert.equal(c.calls[0][0],'update');assert.equal(c.calls[0][1],42);assert(!c.calls.some(x=>x[0]==='insert'));assert(c.calls.some(x=>x[0]==='whatsapp'));
c=context();c.modal.dataset.appointmentId='';await c.saveAppointmentFromForm();assert.deepEqual(c.calls.map(x=>x[0]),['alert']);
c=context();c.updateAppointment=async()=>false;await c.saveAppointmentFromForm();assert.equal(c.calls.length,0);assert.equal(c.button.disabled,false);
c=context();let release;c.updateAppointment=()=>new Promise(r=>release=r);const saving=c.saveAppointmentFromForm();await c.saveAppointmentFromForm();release(true);await saving;assert.equal(c.calls.filter(x=>x[0]==='whatsapp').length,1);
c=context();c.modal.dataset={appointmentId:'',rescheduleMode:'0'};await c.saveAppointmentFromForm();assert.equal(c.calls[0][0],'insert');assert(!c.calls.some(x=>x[0]==='update'));
c=context();c.updateAppointment=async()=>{throw Error('network')};c.console={error(){}};await c.saveAppointmentFromForm();assert(!c.calls.some(x=>x[0]==='whatsapp'));assert.equal(c.appointmentSaveInProgress,false);
for(const fail of [false,true]){c=context();c.closeDateScheduleModal=()=>c.calls.push(['closeDate']);c.closeAppointmentModal=()=>{};c.loadCalendar=async()=>c.calls.push(['reload']);c.showMessage=()=>{};const chain={update(p){assert(!('google_calendar_event_id' in p));return this},eq(k,id){assert.equal(k,'id');assert.equal(id,42);return this},select(s){assert.equal(s,'id');return this},async single(){return {data:fail?null:{id:42},error:fail?{message:'denied'}:null}}};c.supabaseClient={from(t){assert.equal(t,'appointments');return chain}};vm.runInContext(fn('updateAppointment'),c);const result=await c.updateAppointment(42,{customer_name:'Test',mobile_number:'9000000000',appointment_date:'2026-10-10',appointment_time:'10:30'});assert.equal(result,!fail);assert.equal(c.calls.some(x=>x[0]==='reload'),!fail);}
console.log('PASS: 8 reschedule scenarios; all inline scripts parse.');
})().catch(e=>{console.error(e);process.exitCode=1});
